package com.hzlh.kzq.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hzlh.kzq.data.model.ChangjingDatas;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHANGJING_DATAS".
*/
public class ChangjingDatasDao extends AbstractDao<ChangjingDatas, Long> {

    public static final String TABLENAME = "CHANGJING_DATAS";

    /**
     * Properties of entity ChangjingDatas.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Cj_id = new Property(0, Long.class, "cj_id", true, "_id");
        public final static Property Cj_name = new Property(1, String.class, "cj_name", false, "CJ_NAME");
    }


    public ChangjingDatasDao(DaoConfig config) {
        super(config);
    }
    
    public ChangjingDatasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHANGJING_DATAS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: cj_id
                "\"CJ_NAME\" TEXT);"); // 1: cj_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHANGJING_DATAS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChangjingDatas entity) {
        stmt.clearBindings();
 
        Long cj_id = entity.getCj_id();
        if (cj_id != null) {
            stmt.bindLong(1, cj_id);
        }
 
        String cj_name = entity.getCj_name();
        if (cj_name != null) {
            stmt.bindString(2, cj_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChangjingDatas entity) {
        stmt.clearBindings();
 
        Long cj_id = entity.getCj_id();
        if (cj_id != null) {
            stmt.bindLong(1, cj_id);
        }
 
        String cj_name = entity.getCj_name();
        if (cj_name != null) {
            stmt.bindString(2, cj_name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChangjingDatas readEntity(Cursor cursor, int offset) {
        ChangjingDatas entity = new ChangjingDatas( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // cj_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // cj_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChangjingDatas entity, int offset) {
        entity.setCj_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCj_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChangjingDatas entity, long rowId) {
        entity.setCj_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChangjingDatas entity) {
        if(entity != null) {
            return entity.getCj_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChangjingDatas entity) {
        return entity.getCj_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
