package com.hzlh.kzq.data.DbDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hzlh.kzq.data.model.WgDatas;

import com.hzlh.kzq.data.DbDao.WgDatasDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wgDatasDaoConfig;

    private final WgDatasDao wgDatasDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wgDatasDaoConfig = daoConfigMap.get(WgDatasDao.class).clone();
        wgDatasDaoConfig.initIdentityScope(type);

        wgDatasDao = new WgDatasDao(wgDatasDaoConfig, this);

        registerDao(WgDatas.class, wgDatasDao);
    }
    
    public void clear() {
        wgDatasDaoConfig.clearIdentityScope();
    }

    public WgDatasDao getWgDatasDao() {
        return wgDatasDao;
    }

}
