package com.hzlh.kzq.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hzlh.kzq.data.model.WgDatas;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WG_DATAS".
*/
public class WgDatasDao extends AbstractDao<WgDatas, Long> {

    public static final String TABLENAME = "WG_DATAS";

    /**
     * Properties of entity WgDatas.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Wg_id = new Property(0, Long.class, "wg_id", true, "_id");
        public final static Property Wg_ip = new Property(1, String.class, "wg_ip", false, "WG_IP");
        public final static Property Wg_name = new Property(2, String.class, "wg_name", false, "WG_NAME");
        public final static Property Wg_swj_ip = new Property(3, String.class, "wg_swj_ip", false, "WG_SWJ_IP");
        public final static Property Wg_status = new Property(4, int.class, "wg_status", false, "WG_STATUS");
    }


    public WgDatasDao(DaoConfig config) {
        super(config);
    }
    
    public WgDatasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WG_DATAS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: wg_id
                "\"WG_IP\" TEXT," + // 1: wg_ip
                "\"WG_NAME\" TEXT," + // 2: wg_name
                "\"WG_SWJ_IP\" TEXT," + // 3: wg_swj_ip
                "\"WG_STATUS\" INTEGER NOT NULL );"); // 4: wg_status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WG_DATAS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WgDatas entity) {
        stmt.clearBindings();
 
        Long wg_id = entity.getWg_id();
        if (wg_id != null) {
            stmt.bindLong(1, wg_id);
        }
 
        String wg_ip = entity.getWg_ip();
        if (wg_ip != null) {
            stmt.bindString(2, wg_ip);
        }
 
        String wg_name = entity.getWg_name();
        if (wg_name != null) {
            stmt.bindString(3, wg_name);
        }
 
        String wg_swj_ip = entity.getWg_swj_ip();
        if (wg_swj_ip != null) {
            stmt.bindString(4, wg_swj_ip);
        }
        stmt.bindLong(5, entity.getWg_status());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WgDatas entity) {
        stmt.clearBindings();
 
        Long wg_id = entity.getWg_id();
        if (wg_id != null) {
            stmt.bindLong(1, wg_id);
        }
 
        String wg_ip = entity.getWg_ip();
        if (wg_ip != null) {
            stmt.bindString(2, wg_ip);
        }
 
        String wg_name = entity.getWg_name();
        if (wg_name != null) {
            stmt.bindString(3, wg_name);
        }
 
        String wg_swj_ip = entity.getWg_swj_ip();
        if (wg_swj_ip != null) {
            stmt.bindString(4, wg_swj_ip);
        }
        stmt.bindLong(5, entity.getWg_status());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WgDatas readEntity(Cursor cursor, int offset) {
        WgDatas entity = new WgDatas( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // wg_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // wg_ip
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // wg_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // wg_swj_ip
            cursor.getInt(offset + 4) // wg_status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WgDatas entity, int offset) {
        entity.setWg_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWg_ip(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWg_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWg_swj_ip(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWg_status(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WgDatas entity, long rowId) {
        entity.setWg_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WgDatas entity) {
        if(entity != null) {
            return entity.getWg_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WgDatas entity) {
        return entity.getWg_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
